Rails.application.config.assets.version = '1.0'
Rails.application.config.assets.precompile += %w[jquery-3.3.1.min.js]
Rails.application.config.assets.precompile += %w[admin.js]
Rails.application.config.assets.precompile += %w[admin_layout.css]
Rails.application.config.assets.precompile += %w[dropzone.js]
Rails.application.config.assets.precompile += %w[dropzone.css]
Rails.application.config.assets.precompile += %w[bootstrap-tagsinput.js]
Rails.application.config.assets.precompile += %w[bootstrap-tagsinput.css]
Rails.application.config.assets.precompile += %w[style-fc.css]
Rails.application.config.assets.precompile += %w[magnific-popup/magnific-popup.css]
Rails.application.config.assets.precompile += %w[bootstrap.min.css]
Rails.application.config.assets.precompile += %w[bootstrap.min.js]
Rails.application.config.assets.precompile += %w[index/styles-index.css]
Rails.application.config.assets.precompile += %w[home.css]
Rails.application.config.assets.precompile += %w[cart.css]
Rails.application.config.assets.precompile += %w[spectrum.css]
Rails.application.config.assets.precompile += %w[spectrum.js]
Rails.application.config.assets.precompile += %w[jquery.js]
Rails.application.config.assets.precompile += %w[jscolor.js]
Rails.application.config.assets.precompile += %w[application.js]
Rails.application.config.assets.precompile += %w[main.js]
Rails.application.config.assets.precompile += %w[konva.min.js]


